config/routes.rb
Huodong::Application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'

  resources :posts

  devise_for :users

  resources :events do
    resources :tickets, :controller => 'events/tickets'
    resources :fields, :controller => 'events/fields' do
      post :save
    end
  end

  resources :hosts

  resources :orders do
    collection do
      post 'review'
      get 'pay_return'
      post 'pay_notify'
    end
  end

  root :to => 'welcome#index'

end

app/models/host.rb
class Host < ActiveRecord::Base

  STATUS = ['uncertified', 'certified']

  # attr_accessible :title, :body
  belongs_to :user
  has_many :events

  attr_accessible :name, :detail, :telephone, :province, :city, :address, :website, :weibo, :email, :msn, :qq
  validates :name, :presence => true

  def certified?
    status == 'certified'
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  filter_resource_access :no_attribute_check => [:index, :new, :create]

  skip_filter :authenticate_user!, :only => [:show]

  def index
    @hosts = Host.where(:user_id => current_user.id)
  end

  def new
  end

  def create
    @host.user = current_user
    @host.status = 'uncertified'
    if @host.save
      redirect_to hosts_path
    else
      render 'new'
    end

  end

  def edit

  end

  def update
    respond_to do |format|
      if @host.update_attributes(params[:host])
        format.html { redirect_to hosts_path, notice: 'Host was successfully updated.' }
      else
        format.html { render action: "edit" }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  def show

  end

end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/Hosts/_form.html.erb
<% content_for :javascripts do %>
   <script type="text/javascript">
     $(function() {
         <%= render 'shared/regions.js', :resource => @host %>
     })
   </script>
<% end %>

<%= simple_form_for @host, :html => { :class => 'form-horizontal'} do |f| %>
    <fieldset>
        <legend>举办方管理</legend>

        <%= f.input :name, :label => '正式名称' %>

        <%= f.input :detail, :label => '简要介绍' %>

        <%= f.input :telephone, :label => '联系电话' %>

        <%= f.input :time, :label => '办公地点' do %>
          <%= f.input_field :province, :collection => provinces, :prompt => '省/直辖市/自治区' %>
          &nbsp;&nbsp;
          <%= f.input_field :city, :collection => cities[@host.province] || [], :prompt => '市/区' %>
        <% end %>

        <%= f.input :address, :label => '详细地址', :placeholder => '街道/道路号/建筑名' %>

        <%= f.input :address, :label => '官方网站' %>

        <%= f.input :email, :label => 'Email' %>

        <%= f.input :msn, :label => 'MSN' %>

        <%= f.input :qq, :label => 'QQ' %>

        <div class="form-actions">
        <%= f.button :submit, :class => 'btn-primary', :value=> '保存' %>
        <a id="cancel_button" class="btn" href="<%= hosts_path %>">取消</a>
        </div>
    </fieldset>
<% end %>

app/views/Hosts/edit.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to "首页", root_path %> <span class="divider">&raquo;</span></li>
    <li class="active">编辑举办方</li>
<% end %>

<%= render 'form' %>

app/views/Hosts/index.html.erb
<% content_for :stylesheets do %>
    <style type="text/css">

    </style>
<% end %>

<% content_for :javascripts do %>
    <script type="text/javascript">
        $(function() {

        })
    </script>
<% end %>

<% content_for :breadcrumb do %>
    <li><%= link_to "首页", root_path %> <span class="divider">&raquo;</span></li>
    <li class="active">举办方管理</li>
<% end %>

<div class="row">

      <table id="host_table" class="table table-striped span12">
        <caption></caption>
        <thead>
        <tr>
          <th>正式名称</th>
          <th>联系电话</th>
          <th>办公地点</th>
          <th>详细地址</th>
          <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <% if @hosts.blank? %>
            <tr placeholder>
              <td colspan="6">尚未创建任何举办方信息</td>
            </tr>
        <% end %>
        <% @hosts.each do |host| %>
            <tr>
              <td><%= host.name %></td>
              <td><%= host.telephone %></td>
              <td><%= host.province + '-' + host.city %></td>
              <td><%= host.address %></td>
              <td>
                <a href="<%= host_path(host) %>" data-method="DELETE" class="btn btn-danger btn-mini">删除</a>
                <a href="<%= edit_host_path(host) %>" class="btn btn-mini">编辑</a>
              </td>
            </tr>
        <% end %>

        </tbody>
        <tfoot>
        <tr>
          <td colspan="6">
            <a href="<%= new_host_path %>" data-method="GET" class="btn btn-info">增加票种</a>
          </td>
        </tr>
        </tfoot>
      </table>

</div>

app/views/Hosts/new.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to "首页", root_path %> <span class="divider">&raquo;</span></li>
    <li class="active">增加举办方</li>
<% end %>

<%= render 'form' %>