config/routes.rb
Huodong::Application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'

  resources :posts

  devise_for :users

  resources :events do
    resources :tickets, :controller => 'events/tickets'
    resources :fields, :controller => 'events/fields' do
      post :save
    end
  end

  resources :hosts

  resources :orders do
    collection do
      post 'review'
      get 'pay_return'
      post 'pay_notify'
    end
  end

  root :to => 'welcome#index'

end

app/models/event.rb
# -*- encoding : utf-8 -*-
class Event < ActiveRecord::Base
  #-------------------------------------------------------
  # CONSTANTS define, avoid Million-Model march
  #-------------------------------------------------------
  CATEGORIES = ['职场/商务', '沙龙/讲座', '电影', '会议培训', '节庆/集会', '聚会/派对', '运动健身', '户外/旅游', '公益/环保', '会展/博览', '音乐/演出', '艺术/表演']
  STATUS = ['draft', 'approving', 'published', 'cancelled']
  #           |----> cancelled
  #   draft ------> published ---------------> （finished）
  #                             |-----> suspended
  # 对于非认证的组织发布的活动需要审批
  APPROVE_STATUS = ['pending', 'approved', 'reject']

  STATUS.each do |status|
    define_method "#{status}?" do
      self.status == status
    end
  end

  #------------------------------------------------------
  # Relations assiacation
  #------------------------------------------------------
  belongs_to :user
  belongs_to :host
  has_many :tags, :as => :taggable, :dependent => :destroy
  has_many :tickets
  has_many :fields, :as => :fieldable

  has_many :versions, :as => :versionable

  accepts_nested_attributes_for :tickets

  #-----------------------------------------------------
  # Mass assignments
  #-----------------------------------------------------
  attr_accessible :name, :start_time, :end_time, :province, :city, :address,
                  :size, :category, :host_id, :banner,
                  :detail, :seller_name, :seller_email, :seller_telephone,
                  :short_url, :site_url, :notice, :tag_names
  attr_accessible :tickets_attributes

  def tag_names
    @tag_names || self.tags.map {|tag| tag.name}.join(',')
  end

  def tag_names= names
    @tag_names = names
  end
  #-----------------------------------------------------
  # Validations
  #-----------------------------------------------------
  validates :name, :presence => true
  validates :start_time, :presence => true
  validates :end_time, :presence => true
  validates :province, :presence => true
  validates :city, :presence => true
  validates :address, :presence => true
  validates :category, :presence => true, :inclusion => {:in => CATEGORIES }
  validates :detail, :presence => true
  validates :banner, :presence => true
  validates :host_id, :presence => true
  validates :size, :presence => true
  validates :seller_name, :presence => true
  validates :seller_telephone, :presence => true

  #-----------------------------------------------------
  # Lifecycle callbacks
  #-----------------------------------------------------

  after_save :save_tags

  def save_tags
    self.tags.clear
    @tag_names.split(',').each do |name|
      self.tags.create(:name => name)
    end
  end
  # Business Logic
  class << self
    def create_draft_by_user event
      event.id = Event.connection.select_value("SELECT nextval('events_id_seq')")
      version = event.versions.new
      version.data = event
      version.status = 'draft'
      version.save!
    end

    def create_publish_by_user event

      if event.host.certified?
        event.status = 'published'
        event.save!
      else
        event.id = Event.connection.select_value("SELECT nextval('events_id_seq')")
        version = event.versions.new
        version.data = event
        version.status = 'pending'
        version.save!
      end
    end

    def draft_publish version
      Event.transaction do
        version.status = 'pending'
        version.save!
      end
    end

    def approve event
      Event.transaction do
        event.update_attributes!(:approve_flag => '0')
        version = event.versions.last
        version.status = 'approved'
        version.save!
      end
    end

    def reject event
      Event.transaction do
        event.update_attributes!(:approve_flag => '0')
        version = event.versions.last
        version.status = 'rejected'
        version.save!
      end
    end


  end
end

app/controllers/events/fields_controller.rb
# 报名表字段设计
class Events::FieldsController < ApplicationController
  before_filter :load_event
  filter_resource_access

  def index
    @fields = @event.fields
    @fields.each do |field|
      field.options = JSON.parse(field.options) unless field.options.nil?
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    fields = params[:fields]
    index = 0
    fields.each do |key, field|
      field.options = field[:options].to_json unless field[:options].nil?
      if key.start_with? 'new'
        Field.create field
      else
        f = Field.find key.to_i
        f.update_attributes field
      end
    end
  end

  protected
  def load_event
    @event = Event.find(params[:event_id])
  end


end

app/controllers/events/tickets_controller.rb
class Events::TicketsController < ApplicationController

  filter_resource_access :nested_in => :events

  def index
    @tickets = @event.tickets.all
  end

  def show
    @ticket = @event.tickets.find(params[:id])
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = @event.tickets.build(params[:ticket])
    @ticket.available = @ticket.capacity
    @ticket.status = 'on-sale'
    if @ticket.save
      #todo 启动异步JOB, 在指定时间开售
      redirect_to event_tickets_path(@event)
    else
      render 'new'
    end
  end

  def edit
    @ticket = @event.tickets.find(params[:id])
  end

  def update
    @ticket = @event.tickets.find(params[:id])

    if @ticket.update_attributes(params[:ticket])
      redirect_to event_tickets_path(@event)
    else
      render :action => :new
    end

  end

  def destroy
    @ticket = @event.tickets.find(params[:id])
    @ticket.destroy

    redirect_to event_tickets_path(@event)
  end

  def show
    @ticket = @event.tickets.find(params[:id])
  end
end

app/controllers/events_controller.rb
# -*- encoding : utf-8 -*-
class EventsController < ApplicationController
  filter_resource_access :no_attribute_check => [:index, :new, :create]
  # These are the default options for this controller
  #filter_resource_access
  #    :collection => :index,
  #    :new          => [:new, :create],
  #    :member       => [:show, :edit, :update, :destroy],
  #    :nested_in    => nil,
  #    :context      => :conferences,
  #    :no_attribute_check => :index
  #
  # The filter_resource_access is equivalent to the following filter_access_to
  # calls:
  #
  # Before filter to provide the objects for the actions where no params[:id]
  # is available.  See TalksController for a case where this makes sense even
  # for the index action.
  #before_filter :load_conference, :only => [:show, :edit, :update, :destroy]
  #before_filter :new_conference, :only => [:new, :create]
  # Installs a before_filter to check accesses on all actions for the user's
  # authorization.  :attribute_check causes the object in @conference to
  # be checked against the conditions in the authorization rules.
  #filter_access_to :all, :attribute_check => true
  #filter_access_to :index, :attribute_check => false

  skip_filter :authenticate_user!, :only => [:show]

  # 活动Dashboard
  def index
    @events = Event.where(:user_id => current_user.id).order("created_at desc")
  end

  # 创建活动
  def new
    @ticket = @event.tickets.new
  end

  # 创建活动保存
  def create
    @event = Event.new(params[:event])
    @event.user = current_user
    @event.status = params[:action_save_draft] ? 'draft' : 'published'

    if @event.save
      redirect_to events_path
    else
      render 'new'
    end
  end

  def approve
    @event = Event.find(params[:id])
    Event.approve(@event)
  end

  def edit

  end

  def update
    if @event.update_attributes(params[:event])
      redirect_to events_path, notice: 'Event was successfully updated.'
    else
      render "edit"
    end
  end

  def destroy
    @event.destroy

    redirect_to events_path
  end

  def show
    response.headers['Expires'] = '-1'
    response.headers['Cache-Control'] = 'no-cache, no-store'
  end

  # 活动搜索
  def search
    render 'event/search', :layout => 'default'
  end

  # 活动搜索提交
  def search_post

  end
end

app/views/events/_form.html.erb
<%= f.input :name, :label => '活动名称', :help => "给你的活动取一个合适的名字，以便参与者可以一眼明白活动的形式、内容、范围等" %>

<%= f.input :start_time, :label => '举办时间', :required => true do %>
    <%= f.input_field :start_time, :class => "calchooser" %>
    ~
    <%= f.input_field :end_time, :class => "calchooser" %>
<% end %>

<%= f.input :time, :label => '举办地点', :required => true do %>
    <%= f.input_field :province, :collection => provinces, :prompt => '省/直辖市/自治区' %>
    &nbsp;&nbsp;
    <%= f.input_field :city, :collection => cities[@event.province] || [], :prompt => '市/区' %>
<% end %>

<%= f.input :address, :label => '详细地址', :wrapper => 'append' do %>
    <%= f.input_field :address, :placeholder => '街道/道路号/建筑名' %>
    <!-- Button to trigger modal -->
    <a href="#map_window" role="button" class="btn" data-toggle="modal" id="show_map"><i class="icon-map-marker"></i>
      从地图中获取</a>

    <!-- Modal -->
    <div id="map_window" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">地图中位置</h3>
      </div>
      <div id="map_body" class="modal-body" style="width: 530px;height: 300px;overflow: hidden;margin:0;">
      </div>
      <div class="modal-footer">
        <span id="map_address" style="border: dashed 1px #ccc; padding: 5px;"></span>
        <a class="btn btn-primary" id="select_map">确定</a>
        <a class="btn" data-dismiss="modal" aria-hidden="true">取消，我要手动输入</a>
      </div>
    </div>
<% end %>

<%= f.input :size, :label => '最大人数', :help => '免费会员举办活动人数最多为100' %>

<%= f.input :category, :label => '活动类别', :collection => Event::CATEGORIES, :prompt => '请选择..' %>

<%= f.input :host_id, :label => '活动举办方' do %>
    <%= f.input_field :host_id, :label => false, :collection => hosts, :prompt => '请选择..' %>
    <a href="<%= hosts_path %>">新增/编辑</a>
<% end %>


<%= f.input :tag_names, :label => '标签', :help => '标签有利于百度、谷歌搜索，请以逗号(,)或空格分隔多个标签' %>

<%= f.input :banner, :label => '活动海报', :wrapper => 'append', :help => '优秀的活动海报可以聚集更多的人气' do %>
    <%= rich_picker_tag("event[banner]", @event.banner) %>
<% end %>

<%= f.input :detail, :label => '活动简介', :as => :textarea do %>
    <%= rich_editor_tag("event[detail]", @event.detail) %>
<% end %>

<%= f.input :seller_name, :label => '售票人姓名' %>

<%= f.input :seller_telephone, :label => '售票人电话' %>

<%= f.input :seller_email, :label => '售票人邮件' %>

<%= f.input :short_url, :label => '个性URL', :wrapper => 'prepend' do %>
    <span class="add-on">http://www.huodongpai.com/</span>
    <%= f.input_field :short_url, :label => false %>
<% end %>

<%= f.input :site_url, :label => '相关网址', :placeholder => '例如：http://www.yoursite.com' %>

<%= f.input :notice, :label => '注意事项' %>


app/views/events/_form.js.erb
// 标签控件
$('#event_tag_names').tagit({singleField: true});

// 地图选择地址
//            var map = new BMap.Map("map_body");
//            var gc = new BMap.Geocoder();
//            $('#show_map').click(function() {
//                var city = $('select[name="event[city]"]').val()
//                city = city != '' ? city : (remote_ip_info ? remote_ip_info['city'] : '上海')
//
//                map.centerAndZoom(city,15);
//            })
//            map.addEventListener("click", function(e){
//                var pt = e.point;
//                map.clearOverlays()
//                var marker = new BMap.Marker(pt);  // 创建标注
//                map.addOverlay(marker);              // 将标注添加到地图中
//
//                gc.getLocation(pt, function(rs){
//                    var addComp = rs.addressComponents;
//
//                    $("#map_address").html(/*addComp.province + ", " + addComp.city + ", " + */addComp.district + "" + addComp.street + "" + addComp.streetNumber);
//                });
//            });
//            $('a#select_map').click(function() {
//                $('input[name="event[address]"]').val($("#map_address").html())
//                $('#map_window').modal('hide')
//            })

app/views/events/edit.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to "首页", root_path %> <span class="divider">&raquo;</span></li>
    <li><%= link_to "活动管理", events_path %> <span class="divider">&raquo;</span></li>
    <li class="active">活动基本信息</li>
<% end %>

<% content_for :javascripts do %>
    <script type="text/javascript">
        $(function () {
            <%= render 'shared/regions.js', :resource => @event %>
            <%= render 'form.js', :resource => @event %>
        })
    </script>
<% end %>

<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="<%= edit_event_path @event %>">活动基本信息</a></li>
  <li><a href="<%= event_tickets_path @event %>">票务设定</a></li>
  <li><a href="<%= event_fields_path @event %>">报名表设计</a></li>
</ul>

<div id="event" class="row">
  <%= simple_form_for @event, :validate => false, :html => {:class => 'form-horizontal'} do |f| %>
      <fieldset>
        <legend>活动基本信息</legend>
        <%= render 'form', :f => f %>

      </fieldset>

      <div class="form-actions">
        <% if @event.draft? %>
            <%= submit_tag '保存草稿', :name => 'action_save_draft', :class => 'btn btn-primary' %>
        <% end %>
        <%= submit_tag '保存并发布', :name => 'action_publish', :class => 'btn btn-primary' %>
        <%= submit_tag '取消', :type => :reset, :class => "btn btn-danger" %>
      </div>


  <% end %>
</div>

app/views/events/index.html.erb
<% content_for :stylesheets do %>
    <style type="text/css">

    </style>
<% end %>

<% content_for :javascripts do %>
    <script type="text/javascript">

        $(function() {

        })
    </script>
<% end %>

<% content_for :breadcrumb do %>
    <li><%= link_to "首页", root_path %> <span class="divider">&raquo;</span></li>
    <li class="active">活动管理</li>
<% end %>

<div class="btn-group" data-toggle="buttons-radio">
  <button class="btn">上架</button>
  <button class="btn">草稿</button>
  <button class="btn">完成</button>
  <button class="btn">废弃</button>
</div>

<a href="<%= new_event_path %>" class="btn btn-success">发布新活动</a>

<table class="table table-striped">
    <caption></caption>
    <thead>
        <tr>
          <th>活动名称</th>
          <th>活动类型</th>
          <th>举办日期</th>
          <th>举办地点</th>
          <th>报名数</th>
          <th>状态</th>
          <th>操作</th>
        </tr>
    </thead>
    <tbody>
      <% if @events.blank? %>
        <tr placeholder>
          <td colspan="7">尚未有任何发布的活动</td>
        </tr>
      <% end %>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.category %></td>
          <td><%= event.start_time + ' ~ ' + event.end_time %></td>
          <td><%= event.province  + event.city + ' ' + event.address %></td>
          <td><%= event.status %></td>
          <td></td>
          <td>
            <a href="<%= event_path(event) %>" data-method="DELETE" class="btn btn-danger btn-mini">删除</a>
            <a href="<%= edit_event_path(event) %>" class="btn btn-mini">编辑</a>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>


app/views/events/new.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to "首页", root_path %> <span class="divider">&raquo;</span></li>
    <li><%= link_to "活动管理", events_path %> <span class="divider">&raquo;</span></li>
    <li class="active">创建活动</li>
<% end %>

<% content_for :javascripts do %>
    <script id="ticket_row_template" type="text/template">
      <%% var prefix = 'event[tickets_attributes][]' %>
      <tr>
          <td><%%= ticket.name %></td>
          <td><%%= ticket.package %></td>
          <td><%%= ticket.online_price %></td>
          <td><%%= ticket.capacity %></td>
          <td><a class="edit_ticket_button btn btn-mini">编辑</a><a class="delete_ticket_button btn btn-mini">删除</a></td>
          <%% for (var prop in ticket) { %>
          <%% var name = prefix + '[' + prop + ']' %>
          <%% var value = ticket[prop] %>
          <input type="hidden" name="<%%= name %>" value="<%%= value %>">
          <%% } %>
      </tr>
    </script>
    <%= javascript_include_tag 'http://api.map.baidu.com/api?v=1.4' %>
    <%= javascript_include_tag 'http://int.dpool.sina.com.cn/iplookup/iplookup.php?format=js' %>
    <script type="text/javascript">
        $(function () {
            <%= render 'shared/regions.js', :resource => @event %>
            <%= render 'form.js', :resource => @event %>

            /*---------------------票券设定---------------------------------*/
            $('#save_ticket_button').click(function () {
                var that = $(this)
                var params = $('#ticket_form').serializeJSON()

                var row = template('ticket_row_template', {ticket: params.ticket})
                console.log(row)

                if ($('#ticket_form').attr('for') == 'new') {
                    $('#ticket_table tbody').append($(row))
                } else {
                    var index = $('#ticket_form').attr('for')
                    $('#ticket_table tbody tr:eq(' + index + ')').replaceWith($(row))
                }

                $('#ticket_form').hide()
                $('#ticket_table').show()
            })

            $('#cancel_ticket_button').click(function () {
                $('#ticket_form').hide()
                $('#ticket_table').show()
            })

            $('#new_ticket_button').click(function () {
                $('#ticket_form').attr('for', 'new')
                $('#ticket_form :input').val(['']) //clear

                $('#ticket_table').hide()
                $('#ticket_form').show()
            })

            $('.edit_ticket_button').live('click', function () {
                var that = $(this)

                var index = $('#ticket_table tbody tr').index(that.closest('tr'))
                $('#ticket_form').attr('for', index)
                var params = that.closest('tr').serializeJSON()
                params = params.event.tickets_attributes[0]
                for (var prop in params) {
                    var name = 'ticket[' + prop + ']'
                    var value = params[prop]
                    $('#ticket_form :input[name="' + name + '"]').val([value])
                }

                $('#ticket_table').hide()
                $('#ticket_form').show()
            })

            $('.delete_ticket_button').live('click', function () {
                var that = $(this)
                that.closest('tr').remove()
            })
        })
    </script>
<% end %>

<div class="row">

  <%= simple_form_for @event, :validate => false, :html => {:class => 'form-horizontal'} do |f| %>
      <fieldset>
        <legend>活动基本信息</legend>
        <%= render 'form', :f => f %>
      </fieldset>

      <fieldset>
        <legend>票券设定</legend>
        <table id="ticket_table" class="table table-striped">
          <caption></caption>
          <thead>
          <tr>
            <th>票种</th>
            <th>套票</th>
            <th>票价</th>
            <th>数量</th>
            <th>操作</th>
          </tr>
          </thead>
          <tbody>
          </tbody>
          <tfoot>
          <tr>
            <td colspan="6">
              <a class="btn btn-info" id="new_ticket_button">增加票种</a>
            </td>
          </tr>
          </tfoot>
        </table>
        <div id="ticket_form" class="hide well">
          <%= simple_fields_for @ticket do |ff| %>
              <%= render 'events/tickets/form', :f => ff %>
          <% end %>
          <a class="btn btn-info" id="save_ticket_button">保存</a>
          <a class="btn" id="cancel_ticket_button">取消</a>
        </div>
      </fieldset>

      <div class="form-actions">
        <%= submit_tag '保存草稿', :name => 'action_save_draft', :class => 'btn btn-primary' %>
        <%= submit_tag '保存并发布', :name => 'action_publish', :class => 'btn btn-primary' %>
        <%= submit_tag '取消', :type => :reset, :class => "btn btn-danger" %>
      </div>


  <% end %>

</div>

app/views/events/show.html.erb
<div class="span8">
  <img src="<%= @event.banner %>">
  <form action="/orders/check" method="post">
  <input type="hidden" name="event_id" value="<%= @event.id %>" >
  <table class="table table-striped">
    <thead>
    <tr>
      <th>票种</th>
      <th>售票时间</th>
      <th>原价</th>
      <th>售价</th>
      <th>剩余票数</th>
      <th>订购数量</th>
    </tr>
    </thead>
    <tbody>
      <input type="hidden" name="event_id" value="<%= @event.id %>">
      <% @event.tickets.each do |ticket| %>
        <tr>
            <td><%= ticket.name + "(" + ticket.package + ")" %></td>
            <td>截止<%= ticket.sale_end_time.blank? ? ticket.sale_end_time : ticket.event.end_time  %></td>
            <td style="text-decoration: underline;"><%= ticket.offline_price %></td>
            <td><%= ticket.online_price %></td>
            <td><%= ticket.available %></td>
            <td>
              <input type="hidden" name="order[order_items_attributes][][ticket_id]" class="span1" value="<%= ticket.id %>">
              <input type="hidden" name="order[order_items_attributes][][price]" class="span1" value="<%= ticket.online_price %>">
              <input type="number" name="order[order_items_attributes][][quantity]" class="span1" value="0">
            </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="6">
        <input type="submit" value="我要购票" class="btn btn-success pull-right" >
      </td>
    </tr>
    </tfoot>
  </table>
  </form>
</div>

<%= simple_form_for @event.tickets.all, :url => {:controller => :orders, :action => :check } do |f| %>
    <%= f.input :name %>
<% end %>

<div class="span3">
  <h2>活动信息</h2>
  <ul>
    <li>举办城市：<%= @event.province %> <%= @event.city %></li>
    <li>举办地点：<%= @event.address %></li>
    <li>举办时间：<%= @event.start_time + " ~ " + @event.end_time %></li>
  </ul>
</div>