config/routes.rb
Huodong::Application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'

  resources :posts

  devise_for :users

  resources :events do
    resources :tickets, :controller => 'events/tickets'
    resources :fields, :controller => 'events/fields' do
      post :save
    end
  end

  resources :hosts

  resources :orders do
    collection do
      post 'review'
      get 'pay_return'
      post 'pay_notify'
    end
  end

  root :to => 'welcome#index'

end

app/models/event.rb
# -*- encoding : utf-8 -*-
class Event < ActiveRecord::Base
  #-------------------------------------------------------
  # CONSTANTS define, avoid Million-Model march
  #-------------------------------------------------------
  CATEGORIES = ['职场/商务', '沙龙/讲座', '电影', '会议培训', '节庆/集会', '聚会/派对', '运动健身', '户外/旅游', '公益/环保', '会展/博览', '音乐/演出', '艺术/表演']
  STATUS = ['draft', 'approving', 'published', 'cancelled']
  #           |----> cancelled
  #   draft ------> published ---------------> （finished）
  #                             |-----> suspended
  # 对于非认证的组织发布的活动需要审批
  APPROVE_STATUS = ['pending', 'approved', 'reject']

  STATUS.each do |status|
    define_method "#{status}?" do
      self.status == status
    end
  end

  #------------------------------------------------------
  # Relations assiacation
  #------------------------------------------------------
  belongs_to :user
  belongs_to :host
  has_many :tags, :as => :taggable, :dependent => :destroy
  has_many :tickets
  has_many :fields, :as => :fieldable

  has_many :versions, :as => :versionable

  accepts_nested_attributes_for :tickets

  #-----------------------------------------------------
  # Mass assignments
  #-----------------------------------------------------
  attr_accessible :name, :start_time, :end_time, :province, :city, :address,
                  :size, :category, :host_id, :banner,
                  :detail, :seller_name, :seller_email, :seller_telephone,
                  :short_url, :site_url, :notice, :tag_names
  attr_accessible :tickets_attributes

  def tag_names
    @tag_names || self.tags.map {|tag| tag.name}.join(',')
  end

  def tag_names= names
    @tag_names = names
  end
  #-----------------------------------------------------
  # Validations
  #-----------------------------------------------------
  validates :name, :presence => true
  validates :start_time, :presence => true
  validates :end_time, :presence => true
  validates :province, :presence => true
  validates :city, :presence => true
  validates :address, :presence => true
  validates :category, :presence => true, :inclusion => {:in => CATEGORIES }
  validates :detail, :presence => true
  validates :banner, :presence => true
  validates :host_id, :presence => true
  validates :size, :presence => true
  validates :seller_name, :presence => true
  validates :seller_telephone, :presence => true

  #-----------------------------------------------------
  # Lifecycle callbacks
  #-----------------------------------------------------

  after_save :save_tags

  def save_tags
    self.tags.clear
    @tag_names.split(',').each do |name|
      self.tags.create(:name => name)
    end
  end
  # Business Logic
  class << self
    def create_draft_by_user event
      event.id = Event.connection.select_value("SELECT nextval('events_id_seq')")
      version = event.versions.new
      version.data = event
      version.status = 'draft'
      version.save!
    end

    def create_publish_by_user event

      if event.host.certified?
        event.status = 'published'
        event.save!
      else
        event.id = Event.connection.select_value("SELECT nextval('events_id_seq')")
        version = event.versions.new
        version.data = event
        version.status = 'pending'
        version.save!
      end
    end

    def draft_publish version
      Event.transaction do
        version.status = 'pending'
        version.save!
      end
    end

    def approve event
      Event.transaction do
        event.update_attributes!(:approve_flag => '0')
        version = event.versions.last
        version.status = 'approved'
        version.save!
      end
    end

    def reject event
      Event.transaction do
        event.update_attributes!(:approve_flag => '0')
        version = event.versions.last
        version.status = 'rejected'
        version.save!
      end
    end


  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  #abstract_class = true

  set_inheritance_column :ruby_type

  # 在售、售罄、停售
  STATUS = ['on-sale', 'stop']
  # 收费票， 免费票， 入场券（免费）
  TYPES = ['ChargeTicket', 'FreeTicket', 'AdmissionCategory']

  def charge?
    type == 'ChargeTicket'
  end

  def free?
    type == 'FreeTicket'
  end

  #------------------------------------------------------
  # Relations assiacation
  #------------------------------------------------------
  belongs_to :event
  has_many :order_items
  has_many :etickets

  #-----------------------------------------------------
  # Mass assignments
  #-----------------------------------------------------
  attr_accessible :name, :type, :package, :capacity, :online_price, :offline_price, :sale_start_time, :sale_end_time, :order_min, :order_max, :notice

                  #-----------------------------------------------------
  # Validations
  #-----------------------------------------------------
  validates :name, :presence => true
  validates :type, :presence => true


  #-----------------------------------------------------
  # Lifecycle callbacks
  #-----------------------------------------------------
  before_create :make_available_as_capacity
  before_create :make_online_price_as_zero_if_free

  def make_available_as_capacity
    self.available = self.capacity
  end

  def make_online_price_as_zero_if_free
    self.online_price = 0 if self.type == 'FreeTicket'
  end

end

app/controllers/events/fields_controller.rb
# 报名表字段设计
class Events::FieldsController < ApplicationController
  before_filter :load_event
  filter_resource_access

  def index
    @fields = @event.fields
    @fields.each do |field|
      field.options = JSON.parse(field.options) unless field.options.nil?
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    fields = params[:fields]
    index = 0
    fields.each do |key, field|
      field.options = field[:options].to_json unless field[:options].nil?
      if key.start_with? 'new'
        Field.create field
      else
        f = Field.find key.to_i
        f.update_attributes field
      end
    end
  end

  protected
  def load_event
    @event = Event.find(params[:event_id])
  end


end

app/controllers/events/tickets_controller.rb
class Events::TicketsController < ApplicationController

  filter_resource_access :nested_in => :events

  def index
    @tickets = @event.tickets.all
  end

  def show
    @ticket = @event.tickets.find(params[:id])
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = @event.tickets.build(params[:ticket])
    @ticket.available = @ticket.capacity
    @ticket.status = 'on-sale'
    if @ticket.save
      #todo 启动异步JOB, 在指定时间开售
      redirect_to event_tickets_path(@event)
    else
      render 'new'
    end
  end

  def edit
    @ticket = @event.tickets.find(params[:id])
  end

  def update
    @ticket = @event.tickets.find(params[:id])

    if @ticket.update_attributes(params[:ticket])
      redirect_to event_tickets_path(@event)
    else
      render :action => :new
    end

  end

  def destroy
    @ticket = @event.tickets.find(params[:id])
    @ticket.destroy

    redirect_to event_tickets_path(@event)
  end

  def show
    @ticket = @event.tickets.find(params[:id])
  end
end

app/controllers/events_controller.rb
# -*- encoding : utf-8 -*-
class EventsController < ApplicationController
  filter_resource_access :no_attribute_check => [:index, :new, :create]
  # These are the default options for this controller
  #filter_resource_access
  #    :collection => :index,
  #    :new          => [:new, :create],
  #    :member       => [:show, :edit, :update, :destroy],
  #    :nested_in    => nil,
  #    :context      => :conferences,
  #    :no_attribute_check => :index
  #
  # The filter_resource_access is equivalent to the following filter_access_to
  # calls:
  #
  # Before filter to provide the objects for the actions where no params[:id]
  # is available.  See TalksController for a case where this makes sense even
  # for the index action.
  #before_filter :load_conference, :only => [:show, :edit, :update, :destroy]
  #before_filter :new_conference, :only => [:new, :create]
  # Installs a before_filter to check accesses on all actions for the user's
  # authorization.  :attribute_check causes the object in @conference to
  # be checked against the conditions in the authorization rules.
  #filter_access_to :all, :attribute_check => true
  #filter_access_to :index, :attribute_check => false

  skip_filter :authenticate_user!, :only => [:show]

  # 活动Dashboard
  def index
    @events = Event.where(:user_id => current_user.id).order("created_at desc")
  end

  # 创建活动
  def new
    @ticket = @event.tickets.new
  end

  # 创建活动保存
  def create
    @event = Event.new(params[:event])
    @event.user = current_user
    @event.status = params[:action_save_draft] ? 'draft' : 'published'

    if @event.save
      redirect_to events_path
    else
      render 'new'
    end
  end

  def approve
    @event = Event.find(params[:id])
    Event.approve(@event)
  end

  def edit

  end

  def update
    if @event.update_attributes(params[:event])
      redirect_to events_path, notice: 'Event was successfully updated.'
    else
      render "edit"
    end
  end

  def destroy
    @event.destroy

    redirect_to events_path
  end

  def show
    response.headers['Expires'] = '-1'
    response.headers['Cache-Control'] = 'no-cache, no-store'
  end

  # 活动搜索
  def search
    render 'event/search', :layout => 'default'
  end

  # 活动搜索提交
  def search_post

  end
end

app/views/events/tickets/_form.html.erb
<%= f.input :name, :label => '票种名称' %>

<%= f.input :package, :label => '套票', :collection => ['单人票', '双人票', '三人票'], :prompt => '请选择..' %>

<%= f.input :type, :label => '是否收费', :as => :radio_buttons, :collection => [['收费', 'ChargeTicket'], ['免费', 'FreeTicket']] %>

<%= f.input :capacity, :label => '票券总数' %>

<%= f.input :online_price, :label => '网上票价', :wrapper_html => {:class => ('hide' unless @ticket.charge?)} %>

<%= f.input :offline_price, :label => '现场票价', :wrapper_html => {:class => ('hide' unless @ticket.charge?)} %>

<%= f.input :time, :label => '售票起止时间' do %>
    <%= f.input_field :sale_start_time, :class => "calchooser" %>
    ~
    <%= f.input_field :sale_end_time, :class => "calchooser" %>
<% end %>

<%= f.input :time, :label => '每订单限量' do %>
    最少 <%= f.input_field :order_min, :class => 'span1' %>
    ~
    最多 <%= f.input_field :order_max, :class => 'span1' %>
<% end %>


app/views/events/tickets/edit.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to "首页", root_path %> <span class="divider">&raquo;</span></li>
    <li><%= link_to "活动管理", events_path %> <span class="divider">&raquo;</span></li>
    <li class="active">编辑票券</li>
<% end %>

<ul class="nav nav-tabs" id="myTab">
  <li><a href="<%= edit_event_path @event %>">活动基本信息</a></li>
  <li class="active"><a href="<%= event_tickets_path @event %>">票务设定</a></li>
  <li><a href="<%= event_fields_path @event %>">报名表设计</a></li>
</ul>

<%= simple_form_for [@event, @ticket], :html => {:class => 'form-horizontal'} do |f| %>
    <fieldset>
      <legend>票券设定(非必填)</legend>
      <%= render 'form', :f => f %>
      <div class="form-actions">
        <%= f.button :submit, :class => 'btn-primary', :value => '保存' %>
        <%= submit_tag '取消', :type => :reset, :class => "btn" %>
      </div>
    </fieldset>
<% end %>

app/views/events/tickets/index.html.erb
<% content_for :stylesheets do %>
    <style type="text/css">

    </style>
<% end %>

<% content_for :javascripts do %>
    <script type="text/javascript">

           $(function() {
                // 取消保存
                $("#cancel_ticket").click(function(e) {
                    e.preventDefault();
                    $("#ticket_table").show()
                    $("#ticket_form").hide()
                })

            })
    </script>
<% end %>

<% content_for :breadcrumb do %>
    <li><%= link_to "首页", root_path %> <span class="divider">&raquo;</span></li>
    <li><%= link_to "活动管理", events_path %> <span class="divider">&raquo;</span></li>
    <li class="active">票券设定</li>
<% end %>

<ul class="nav nav-tabs" id="myTab">
  <li><a href="<%= edit_event_path @event %>">活动基本信息</a></li>
  <li class="active"><a href="<%= event_tickets_path @event %>">票务设定</a></li>
  <li><a href="<%= event_fields_path @event %>">报名表设计</a></li>
</ul>


<div class="row">
    <table id="ticket_table" class="table table-striped">
        <caption></caption>
        <thead>
        <tr>
          <th>票种</th>
          <th>套票</th>
          <th>票价</th>
          <th>数量</th>
          <th>操作</th>
        </tr>
        </thead>
        <tbody>
            <% if @tickets.blank? %>
            <tr placeholder>
              <td colspan="5">尚未建立任何票种! 单纯免费报名的活动可以不添加票券</td>
            </tr>
            <% else %>
            <% @tickets.each do |ticket| %>
            <tr>
              <td><%= ticket.name %></td>
              <td><%= ticket.package %></td>
              <td><%= ticket.online_price %></td>
              <td><%= ticket.capacity %></td>
              <td>
                <a href="<%= event_ticket_path(@event, ticket) %>" data-method="DELETE" class="btn btn-danger btn-mini" data-confirm="你确定要删除该票种吗？">删除</a>
                <a href="<%= edit_event_ticket_path(@event, ticket) %>" data-method="GET" class="btn btn-mini">编辑</a>
              </td>
            </tr>
            <% end %>
            <% end %>

        </tbody>
        <tfoot>
            <tr>
              <td colspan="6">
                <a href="<%= new_event_ticket_path(@event) %>" class="btn btn-info">增加票种</a>
              </td>
            </tr>
        </tfoot>
    </table>

    <div class="form-actions">
      <a class="btn btn-primary" href="<%= event_fields_path @event %>">下一步&raquo;</a>
    </div>
</div>

app/views/events/tickets/new.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to "首页", root_path %> <span class="divider">&raquo;</span></li>
    <li><%= link_to "活动管理", events_path %> <span class="divider">&raquo;</span></li>
    <li class="active">增加票券</li>
<% end %>

<ul class="nav nav-tabs" id="myTab">
  <li><a href="<%= edit_event_path @event %>">活动基本信息</a></li>
  <li class="active"><a href="<%= event_tickets_path @event %>">票务设定</a></li>
  <li><a href="<%= event_fields_path @event %>">报名表设计</a></li>
</ul>

<%= simple_form_for [@event, @ticket], :html => {:class => 'form-horizontal'} do |f| %>
    <fieldset>
      <legend>票券设定(非必填)</legend>
      <%= render 'form', :f => f %>
      <div class="form-actions">
        <%= f.button :submit, :class => 'btn-primary', :value => '保存' %>
        <%= submit_tag '取消', :type => :reset, :class => "btn" %>
      </div>
    </fieldset>
<% end %>